#!/bin/bash
################################################################################
# agent-delegate-with-unique-bran.sh
# Purpose: Create agent AID with unique BRAN and delegate to OOR holder
# Usage: ./agent-delegate-with-unique-bran.sh <agent_alias> <oor_holder_alias>
#
# This script:
#   1. Reads the pre-generated unique BRAN for the agent
#   2. Creates the agent AID using that BRAN as the passcode
#   3. Initiates delegation request from agent to OOR holder
#   4. OOR holder approves the delegation
#   5. Agent completes the delegation
################################################################################

set -e

AGENT_ALIAS=$1
OOR_HOLDER_ALIAS=$2

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

if [ -z "$AGENT_ALIAS" ] || [ -z "$OOR_HOLDER_ALIAS" ]; then
    echo -e "${RED}Usage: $0 <agent_alias> <oor_holder_alias>${NC}"
    echo "Example: $0 jupiterSellerAgent Jupiter_Chief_Sales_Officer"
    exit 1
fi

# Read the pre-generated BRAN
BRAN_FILE="./task-data/${AGENT_ALIAS}-bran.txt"
if [ ! -f "$BRAN_FILE" ]; then
    echo -e "${RED}ERROR: BRAN file not found: $BRAN_FILE${NC}"
    echo "BRAN should have been generated by generate-unique-agent-brans.sh"
    exit 1
fi

AGENT_BRAN=$(cat "$BRAN_FILE")

echo -e "${BLUE}Creating agent ${AGENT_ALIAS} with unique BRAN and delegating to ${OOR_HOLDER_ALIAS}...${NC}"
echo "  BRAN: ${AGENT_BRAN:0:20}... (256-bit)"

# Source environment variables
source ./task-scripts/workshop-env-vars.sh

# Use the existing person-delegate-agent-create script but pass the BRAN as the passcode
# This creates the agent AID with the unique BRAN and initiates delegation
echo -e "${BLUE}→ Creating agent and requesting delegation...${NC}"

docker compose exec tsx-shell \
  /vlei/tsx-script-runner.sh person/person-delegate-agent-create.ts \
    'docker' \
    "${AGENT_BRAN}" \
    "/task-data" \
    "${OOR_HOLDER_ALIAS}" \
    "${AGENT_ALIAS}"

if [ ! -f "./task-data/${AGENT_ALIAS}-delegate-info.json" ]; then
    echo -e "${RED}✗ Failed to create agent delegation request${NC}"
    exit 1
fi

AGENT_AID=$(cat "./task-data/${AGENT_ALIAS}-delegate-info.json" | jq -r '.aid')
echo -e "${GREEN}✓ Agent created and delegation requested${NC}"
echo "  Agent AID: ${AGENT_AID}"

# OOR holder approves delegation
echo -e "${BLUE}→ OOR holder approving delegation...${NC}"
./task-scripts/person/person-approve-agent-delegation.sh "${OOR_HOLDER_ALIAS}" "${AGENT_ALIAS}"

# Agent completes delegation
echo -e "${BLUE}→ Agent completing delegation...${NC}"
./task-scripts/agent/agent-aid-delegate-finish.sh "${AGENT_ALIAS}" "${OOR_HOLDER_ALIAS}"

# Update agent info file to include BRAN reference
if [ -f "./task-data/${AGENT_ALIAS}-info.json" ]; then
    # Add hasUniqueBran flag
    jq '. + {hasUniqueBran: true, branFile: "'${BRAN_FILE}'"}' "./task-data/${AGENT_ALIAS}-info.json" > "./task-data/${AGENT_ALIAS}-info.tmp.json"
    mv "./task-data/${AGENT_ALIAS}-info.tmp.json" "./task-data/${AGENT_ALIAS}-info.json"
fi

echo -e "${GREEN}✓ Agent ${AGENT_ALIAS} delegation complete with unique BRAN${NC}"
echo "  Agent AID: ${AGENT_AID}"
echo "  Delegated to: ${OOR_HOLDER_ALIAS}"
echo "  Unique BRAN: ${AGENT_BRAN:0:20}..."
echo "  Info: ./task-data/${AGENT_ALIAS}-info.json"

exit 0
